# Ограничения для книг
TITLE_MAX_LENGTH = 500
AUTHOR_MAX_LENGTH = 300
GENRE_MAX_LENGTH = 100
DESCRIPTION_MAX_LENGTH = None  # Unlimited
ISBN_MAX_LENGTH = 20

# Валидация
PAGES_MIN = 1
YEAR_MIN = 1000
YEAR_MAX = 2100

# OpenLibrary API
OPENLIBRARY_DEFAULT_TITLE = "Unknown Title"
OPENLIBRARY_MIN_RATING = 0.0
OPENLIBRARY_MAX_RATING = 5.0
OPENLIBRARY_MIN_COVER_ID = 0

# Pagination
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100


# for schemas in openlibrary
MAX_TITLE_LENGTH = 500
DEFAULT_TITLE = "Unknown Title"
MIN_PUBLISH_YEAR = 1000
MAX_PUBLISH_YEAR = 2100
MIN_RATING = 0.0
MAX_RATING = 5.0
MIN_COVER_ID = 0
