"""add composite and partial indexes for books

Revision ID: dcfd3fecee88
Revises: b0416556719b
Create Date: 2025-12-13 23:12:06.458304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcfd3fecee88'
down_revision: Union[str, None] = 'b0416556719b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_books_author_genre', 'books', ['author', 'genre'], unique=False)
    op.create_index('idx_books_available_title_author', 'books', ['title', 'author'], unique=False, postgresql_where=sa.text('available = true'))
    op.create_index('idx_books_title_author', 'books', ['title', 'author'], unique=False)
    op.create_index('idx_books_year_available', 'books', ['year', 'available'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_books_year_available', table_name='books')
    op.drop_index('idx_books_title_author', table_name='books')
    op.drop_index('idx_books_available_title_author', table_name='books', postgresql_where=sa.text('available = true'))
    op.drop_index('idx_books_author_genre', table_name='books')
    # ### end Alembic commands ###
